# Generated by Django 5.0.3 on 2024-03-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='meuApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ip', models.IntegerField(verbose_name='id do ip')),
                ('continentCode', models.CharField(max_length=10, verbose_name='Código do continente')),
                ('continentName', models.CharField(max_length=250, verbose_name='Nome do continente')),
                ('countryCode', models.CharField(max_length=10, verbose_name='Código do país')),
                ('countryName', models.CharField(max_length=250, verbose_name='Nome do país')),
                ('countryNameNative', models.CharField(max_length=250, verbose_name='Nome do país de origem')),
                ('reionCode', models.CharField(max_length=10, verbose_name='Código da região')),
                ('regionName', models.CharField(max_length=100, verbose_name='Nome da região do país')),
                ('city', models.CharField(max_length=250, verbose_name='Nome da cidade')),
                ('postalCode', models.CharField(max_length=100, verbose_name='Código postal')),
                ('latitude', models.CharField(max_length=100, verbose_name='Latitute')),
                ('longitude', models.CharField(max_length=100, verbose_name='Longitute')),
                ('phoneCode', models.CharField(max_length=100, verbose_name='Código do número')),
            ],
        ),
    ]
